# Separate service for stable IP address
kind: Service
apiVersion: v1
metadata:
  name: soavirt-service
spec:
  selector:
    tag: soavirt
  ports:
    - name: http
      port: 9080
      protocol: TCP
    - name: events
      port: 9617
      protocol: TCP
    - name: statistics
      port: 9618
      protocol: TCP
