kind: Service
apiVersion: v1
metadata:
  name: ctp-service
spec:
  selector:
    tag: ctp
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
